=== 1065585676/AgilorIBMSApp/biad/AgilorPointTable/RuleDef.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="RuleDef" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="RuleDef">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="Name " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAACtX6GqaiFzS6XmWuxgfwmpAAAAAFRbTYBL/uJAAAAAAAAAAABSAHUA
bABlAEQAZQBmAAAAAAAAAJlaKqLJ2ZpDnBD1T4mVWcQHAAAArV+hqmohc0ul5lrs
YH8JqU4AYQBtAGUAAAAAAAAAu66PVXnpA06QspNuzQzoiQcAAACtX6GqaiFzS6Xm
WuxgfwmpRQB2AGUAbgB0AAAAAAAAAHHTJtszq95LqNK4aSR6i1YHAAAArV+hqmoh
c0ul5lrsYH8JqUMAbwBuAGQAaQB0AGkAbwBuAAAAAAAAALpRhn/uRUFAikpRyP13
oxUHAAAArV+hqmohc0ul5lrsYH8JqUEAYwB0AGkAbwBuAAAAAAAAAN6Nx1L0DY9D
nmH86hoVDvoHAAAArV+hqmohc0ul5lrsYH8JqUQAZQBzAGMAcgBpAHAAdABpAG8A
bgAAAAAAAAA32ERfhMOySrjAxb3sYvExBwAAAK1foapqIXNLpeZa7GB/CalWAGEA
bABpAGQAAAAAAAAAPM0p45hIGkmr7UImSlynrgcAAACtX6GqaiFzS6XmWuxgfwmp
QQB1AHQAbwBMAG8AYQBkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAAgAAAAAA
AAAAAAAAAAAAAAAA
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="GUID" type="9" value="rV+hqmohc0ul5lrsYH8JqQ==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="Name" minOccurs="1" od:jetType="text" od:sqlSType="nvarchar" od:nonNullable="yes">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="1"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="1"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="mVoqosnZmkOcEPVPiZVZxA==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="16"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Event" minOccurs="1" od:jetType="memo" od:sqlSType="ntext" od:nonNullable="yes">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="3585"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="1"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="0"/>
<od:fieldProperty name="IMEMode" type="2" value="1"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="u66PVXnpA06QspNuzQzoiQ==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="536870910"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Condition" minOccurs="1" od:jetType="memo" od:sqlSType="ntext" od:nonNullable="yes">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="1"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="0"/>
<od:fieldProperty name="IMEMode" type="2" value="1"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="cdMm2zOr3kuo0rhpJHqLVg==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="536870910"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Action" minOccurs="1" od:jetType="memo" od:sqlSType="ntext" od:nonNullable="yes">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="3555"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="1"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="0"/>
<od:fieldProperty name="IMEMode" type="2" value="1"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="ulGGf+5FQUCKSlHI/XejFQ==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="536870910"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Description" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="1"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="3o3HUvQNj0OeYfzqGhUO+g==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="128"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Valid" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Format" type="10" value="Yes/No"/>
<od:fieldProperty name="DefaultValue" type="12" value="True"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="106"/>
<od:fieldProperty name="GUID" type="9" value="N9hEX4TDskq4wMW97GLxMQ==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="AutoLoad" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Format" type="10" value="Yes/No"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="106"/>
<od:fieldProperty name="DefaultValue" type="12" value="True"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== 1065585676/AgilorIBMSApp/biad/AgilorPointTable/RuleDef.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="RuleDef.xsd" generated="2017-11-27T13:49:03">
<RuleDef>
<Name>FCU7_01FanAuto</Name>
<Event>OnTimer(&quot;Timer.FCU7_01FanAuto_Tmr0&quot;,3)</Event>
<Condition>true</Condition>
<Action>string tagBaseName = &quot;Agilor.FCU_F7_7_1&quot;;
string tagTempName, tagTempSetName;
string tagFanSpeedHighName, tagFanSpeedMidName, tagFanSpeedLowName;
string tagCoolValveCtrl;
tagTempName = tagBaseName + &quot;_Temp&quot;;
tagTempSetName = tagBaseName + &quot;_TempSet&quot;;
tagFanSpeedHighName = tagBaseName + &quot;_FanSpeedHigh&quot;;
tagFanSpeedMidName = tagBaseName + &quot;_FanSpeedMid&quot;;
tagFanSpeedLowName = tagBaseName + &quot;_FanSpeedLow&quot;;
tagCoolValveCtrl = tagBaseName + &quot;_CoolValveCtrl&quot;;

float tempDiff = 0;
tempDiff = ToFloat(TagVal(tagTempSetName)) - TagVal(tagTempName);
float coolValve = 0;
if(tempDiff &lt; 0){
    coolValve = 0;
    tempDiff = -1 * tempDiff;
} else {
    coolValve = 1;
}
string fanSpeed = &quot;FanSpeedClose&quot;;
if(tempDiff &gt; 2 * FAN_AUTO_TEMP_DIFF){
    fanSpeed = &quot;FanSpeedHigh&quot;;
} else if(tempDiff &gt; 1 * FAN_AUTO_TEMP_DIFF){
    fanSpeed = &quot;FanSpeedMid&quot;;
} else if(tempDiff &gt; 0) {
    fanSpeed = &quot;FanSpeedLow&quot;;
}

if(fanSpeed == &quot;FanSpeedHigh&quot; and TagVal(tagFanSpeedHighName) != 1){
    if(TagVal(tagFanSpeedMidName) == 1){
        SetTagVal(tagFanSpeedMidName, 0, true);
    }
    if(TagVal(tagFanSpeedLowName) == 1){
        SetTagVal(tagFanSpeedLowName, 0, true);
    }
    SetTagVal(tagFanSpeedHighName, 1, true);
} else if(fanSpeed == &quot;FanSpeedMid&quot; and TagVal(tagFanSpeedMidName) != 1){
    if(TagVal(tagFanSpeedHighName) == 1){
        SetTagVal(tagFanSpeedHighName, 0, true);
    }
    if(TagVal(tagFanSpeedLowName) == 1){
        SetTagVal(tagFanSpeedLowName, 0, true);
    }
    SetTagVal(tagFanSpeedMidName, 1, true);
} else if(fanSpeed == &quot;FanSpeedLow&quot; and TagVal(tagFanSpeedLowName) != 1){
    if(TagVal(tagFanSpeedHighName) == 1){
        SetTagVal(tagFanSpeedHighName, 0, true);
    }
    if(TagVal(tagFanSpeedMidName) == 1){
        SetTagVal(tagFanSpeedMidName, 0, true);
    }
    SetTagVal(tagFanSpeedLowName, 1, true);
} else if(fanSpeed == &quot;FanSpeedClose&quot;){
    if(TagVal(tagFanSpeedHighName) == 1){
        SetTagVal(tagFanSpeedHighName, 0, true);
    }
    if(TagVal(tagFanSpeedMidName) == 1){
        SetTagVal(tagFanSpeedMidName, 0, true);
    }
    if(TagVal(tagFanSpeedLowName) == 1){
        SetTagVal(tagFanSpeedLowName, 0, true);
    }
}

if(TagVal(tagCoolValveCtrl) != coolValve){
    SetTagVal(tagCoolValveCtrl, coolValve, true);
}
printf(&quot;Finish Auto Rule:&quot; + tagBaseName);</Action>
<Description></Description>
<Valid>0</Valid>
<AutoLoad>1</AutoLoad>
</RuleDef>
<RuleDef>
<Name>FCU7_01Change</Name>
<Event>OnChange(&quot;Agilor.FCU_F7_7_1_FanSpeedLow&quot;) or OnChange(&quot;Agilor.FCU_F7_7_1_FanSpeed&quot;) or OnChange(&quot;Agilor.FCU_F7_7_1_FanSpeedMid&quot;) or OnChange(&quot;Agilor.FCU_F7_7_1_FanSpeedHigh&quot;)</Event>
<Condition>true</Condition>
<Action>string tagBaseName = &quot;Agilor.FCU_F7_7_1&quot;;
string autoRuleName = &quot;FCU7_01FanAuto&quot;;
string tagFanSpeedName, tagFanSpeedHighName, tagFanSpeedMidName, tagFanSpeedLowName;
tagFanSpeedName = tagBaseName + &quot;_FanSpeed&quot;;
tagFanSpeedHighName = tagBaseName + &quot;_FanSpeedHigh&quot;;
tagFanSpeedMidName = tagBaseName + &quot;_FanSpeedMid&quot;;
tagFanSpeedLowName = tagBaseName + &quot;_FanSpeedLow&quot;;

string eventSourceName;
eventSourceName = EventSourceName();
if(eventSourceName == tagFanSpeedHighName and TagVal(tagFanSpeedHighName) == 1 and TagVal(tagFanSpeedName) != &quot;FanSpeedAuto&quot;){
    SetTagVal(tagFanSpeedName, &quot;FanSpeedHigh&quot;, false);
} else if(eventSourceName == tagFanSpeedLowName and TagVal(tagFanSpeedLowName) == 1 and TagVal(tagFanSpeedName) != &quot;FanSpeedAuto&quot;){
    SetTagVal(tagFanSpeedName, &quot;FanSpeedLow&quot;, false);
} else if(eventSourceName == tagFanSpeedMidName and TagVal(tagFanSpeedMidName) == 1 and TagVal(tagFanSpeedName) != &quot;FanSpeedAuto&quot;){
    SetTagVal(tagFanSpeedName, &quot;FanSpeedMid&quot;, false);
} else if(eventSourceName == tagFanSpeedName and TagVal(tagFanSpeedName) == &quot;FanSpeedHigh&quot;){
    DisableRule(autoRuleName);
    if(TagVal(tagFanSpeedMidName) == 1){
        SetTagVal(tagFanSpeedMidName, 0, true);
    }
    if(TagVal(tagFanSpeedLowName) == 1){
        SetTagVal(tagFanSpeedLowName, 0, true);
    }
    if(TagVal(tagFanSpeedHighName) != 1){
        SetTagVal(tagFanSpeedHighName, 1, true);
    }
} else if(eventSourceName == tagFanSpeedName and TagVal(tagFanSpeedName) == &quot;FanSpeedMid&quot;){
    DisableRule(autoRuleName);
    if(TagVal(tagFanSpeedHighName) == 1){
        SetTagVal(tagFanSpeedHighName, 0, true);
    }
    if(TagVal(tagFanSpeedLowName) == 1){
        SetTagVal(tagFanSpeedLowName, 0, true);
    }
    if(TagVal(tagFanSpeedMidName) != 1){
        SetTagVal(tagFanSpeedMidName, 1, true);
    }
} else if(eventSourceName == tagFanSpeedName and TagVal(tagFanSpeedName) == &quot;FanSpeedLow&quot;){
    DisableRule(autoRuleName);
    if(TagVal(tagFanSpeedHighName) == 1){
        SetTagVal(tagFanSpeedHighName, 0, true);
    }
    if(TagVal(tagFanSpeedMidName) == 1){
        SetTagVal(tagFanSpeedMidName, 0, true);
    }
    if(TagVal(tagFanSpeedLowName) != 1){
        SetTagVal(tagFanSpeedLowName, 1, true);
    }
} else if(eventSourceName == tagFanSpeedName and TagVal(tagFanSpeedName) == &quot;FanSpeedClose&quot;){
    DisableRule(autoRuleName);
    if(TagVal(tagFanSpeedHighName) == 1){
        SetTagVal(tagFanSpeedHighName, 0, true);
    }
    if(TagVal(tagFanSpeedMidName) == 1){
        SetTagVal(tagFanSpeedMidName, 0, true);
    }
    if(TagVal(tagFanSpeedLowName) == 1){
        SetTagVal(tagFanSpeedLowName, 0, true);
    }
} else if(eventSourceName == tagFanSpeedName and TagVal(tagFanSpeedName) == &quot;FanSpeedAuto&quot;){
    EnableRule(autoRuleName);
} else if(eventSourceName == tagFanSpeedName){
    printf(&quot;Error: &quot; + tagBaseName + &quot; FanSpeed Value(&quot; + TagVal(tagFanSpeedName) + &quot;) Error!&quot;);
    SetTagVal(tagFanSpeedName, &quot;FanSpeedClose&quot;, false);
}</Action>
<Description></Description>
<Valid>1</Valid>
<AutoLoad>1</AutoLoad>
</RuleDef>
</dataroot>
